accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mypage_1/<int:pk>/', views.mypage_1, name='mypage_1'),
    path('update/', views.update, name='update'),
    path('mypage_2/<int:pk>/', views.mypage_2, name='mypage_2'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("c_create/<int:pk>", views.c_create, name="c_create"),
    path("c_delete/<int:a_pk>/<int:c_pk>", views.c_delete, name="c_delete"),
    path("like/<int:pk>", views.like, name="like"),
    path("notice/", views.notice, name="notice"),
    path("notice/n_create/", views.n_create, name="n_create"),
    path("notice/n_detail/<int:pk>", views.n_detail, name="n_detail"),
    path("notice/n_delete/<int:pk>", views.n_delete, name="n_delete"),
    path("notice/n_update/<int:pk>", views.n_update, name="n_update"),
    path("reviews/", views.reviews, name="reviews"),
    path("reviews/create", views.r_create, name="r_create"),
    path("reviews/<int:pk>", views.r_detail, name="r_detail"),
    path("reviews/delete/<int:pk>", views.r_delete, name="r_delete"),
    path("reviews/update/<int:pk>", views.r_update, name="r_update"),
    path("reviews/c_create/<int:pk>", views.r_c_create, name="r_c_create"),
    path("reviews/c_delete/<int:a_pk>/<int:c_pk>", views.r_c_delete, name="r_c_delete"),
    path("reviews/like/<int:pk>", views.r_like, name="r_like"),
    path("faq/", views.faq, name="faq"),
    path("faq/faq_create/", views.faq_create, name="faq_create"),
    path("faq/faq_detail/<int:pk>", views.faq_detail, name="faq_detail"),
    path("faq/faq_delete/<int:pk>", views.faq_delete, name="faq_delete"),
    path("faq/faq_update/<int:pk>", views.faq_update, name="faq_update"),
    path("search/", views.search, name="search"),
    path("searchfail/", views.searchfail, name="searchfail"),
    path("qna/", views.qna, name="qna"),
    path("qna/qna_create/", views.qna_create, name="qna_create"),
    path("qna/qna_detail/<int:pk>", views.qna_detail, name="qna_detail"),
    path("qna/qna_delete/<int:pk>", views.qna_delete, name="qna_delete"),
    path("qna/qna_update/<int:pk>", views.qna_update, name="qna_update"),
    path("qna_c_create/<int:pk>", views.qna_c_create, name="qna_c_create"),
    path("qna_c_delete/<int:a_pk>/<int:c_pk>", views.qna_c_delete, name="qna_c_delete"),
    path("product_main", views.product_main, name="product_main"),
    path("product_detail/<int:pk>", views.product_detail, name="product_detail"),
    path("wishlist/<int:pk>", views.wishlist, name="wishlist"),
    path("wishitem/<int:pk>", views.wishitem, name="wishitem"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.processors import ResizeToFill
from imagekit.models import ProcessedImageField

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )
    user_img = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(60, 60)],
        format="JPEG",
        options={"quality": 50},
        null=True,
    )

    @property
    def full_name(self):
        return f"{self.last_name}{self.first_name}"

articles/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="articles/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )

    thumbnail = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[Thumbnail(200, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Notice(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Review(models.Model):
    country = models.CharField(max_length=10)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    image_two = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    thumbnail = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[Thumbnail(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_reviews"
    )
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_review"
    )


class ReviewComment(models.Model):
    content = models.TextField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Product(models.Model):
    title = models.CharField(max_length=100)
    image = ProcessedImageField(
        upload_to="reviews/",
        blank=True,
        processors=[Thumbnail(400, 300)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    wishlist = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="product_wishlist"
    )

    # def __str__(self):
    #     return self.title
    # def __str__(self):
    #     return self.wishlist

class WishItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Faq(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Qna(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class QnaComment(models.Model):
    content = models.TextField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    qna = models.ForeignKey(Qna, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    PasswordChangeForm,
)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "last_name", "first_name", "email", "user_img")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "last_name", "first_name", "email", "user_img")

accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .forms import (
    CustomUserCreationForm,
    CustomUserChangeForm,
)
from django.contrib.auth import get_user_model, update_session_auth_hash
from email import message
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("accounts:login")
    else:
        form = CustomUserCreationForm()

    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "articles:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


def logout(request):
    auth_logout(request)
    return redirect("articles:index")


def mypage_1(request, pk):
    user = get_user_model().objects.get(pk=pk)

    context = {
        "user": user,
    }
    return render(request, "accounts/mypage_1.html", context)


def mypage_2(request, pk):
    user = get_user_model().objects.get(pk=pk)
    print(user.product_wishlist.all())
    context = {
        "user": user,
    }
    return render(request, "accounts/mypage_2.html", context)


@login_required
def follow(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if request.user == user:
        messages.warning(request, "스스로 팔로우 할 수 없습니다.")
        return redirect("accounts:mypage_2", pk)

    if request.user in user.followers.all():
        user.followers.remove(request.user)
    else:
        user.followers.add(request.user)

    return redirect("accounts:mypage_2", pk)


def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:mypage_1", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)

    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<div class="container py-5">
  <div style="border-radius: 3%; border: 3px solid #FFED90;" class="mx-auto col-md-6 col-10 bg-white p-5">
    <div class="text-center">
      <h1 style="color: #FFED90;" class="mb-3">누런 풍선</h1>
      <p>무거운 여행을 시작해 보세요 :) </p>
    </div>
    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-grid gap-2">
              <button style="background-color: #FFED90;" type="submit" class="m-3 btn btn-lg">✈ 바로 시작 ✈</button>
            </div>
        </form>
        <div class="text-center">
        <small>
          <span>혹시 회원이 아니신가요? <a style="text-decoration: none;" href="{% url 'accounts:signup' %}">회원 가입</a>하기</span>
        </small>
      </div>
    </div> 
  </div>
</div>

{% comment %} <div class="py-5 text-center">
    <div class="py-5 container">
      <div class="row">
        <div style="border-radius: 3%; border: 3px solid #FFED90;" class="mx-auto col-md-6 col-10 bg-white p-5">
          <h2 style="color: #FFED90;" class="mb-3">누런 풍선</h2>
          <p>무거운 여행을 시작해 보세요 :) </p>
          <form action="" method="POST">
            {% csrf_token %}
            
            {% for i in form %}
            <div class="form-group mb-3" style="border-radius: 3%; border: 3px solid #FFED90;"> 
              {{ i }}
            </div>
            {% endfor %}
            </div>
            {% comment %} <div class="form-group mb-3"> 
                <label for="form9"></label>
                <input name="email" style="border-radius: 3%; border: 3px solid #FFED90;" type="email" class="form-control" placeholder="이메일을 입력해주세요." id="form9"> </div>
            <div class="form-group mb-3"> 
                <label for="form10"></label>
                <input name="password" style="border-radius: 3%; border: 3px solid #FFED90;" type="password" class="form-control" placeholder="비밀번호를 입력해주세요." id="form10">
              <br>
              <small>
                <span>혹시 회원이 아니신가요? <a style="text-decoration: none;" href="{% url "accounts:signup" %}">회원 가입</a>하기</span>
              </small>
            </div> 
            <button style="background-color: #FFED90;" type="submit" class="m-2 btn btn-lg">✈ 바로 시작 ✈</button>
          </form> {% endcomment %}
        </div>
      </div>
    </div>
  </div>
{% endblock body %}

accounts/templates/accounts/mypage_1.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="py-5">
    <div style="border-radius: 3%; border: 3px solid #FFED90;" class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-4"></div>
            <div class="d-flex justify-content-center col-md-4 mt-4">
              {% if user.user_img %}
                <img class="m-3 rounded-circle" src="{{ user.user_img.url }}" alt="{{ user.user_img }}" style="width:100px;">
              {% else %}
                <img class="m-3 rounded-circle" src="https://cdn-icons-png.flaticon.com/512/4140/4140048.png" alt="{{ user.user_img }}" style="width:100px;">
              {% endif %}
            </div>
            <div class="col-md-4 text-right p-3">
              <a style="border: 3px solid #FFED90;" class="btn" href="{% url 'accounts:update' %}">편집하기</a>
            </div>
          </div>
          <div class="row">
            <div class="m-2 col-md-12 mb-5 ms-4">
              <p>
                <span class="fw-bold fs-5">닉네임&nbsp; :</span>
                {{ user.username }}
              </p>
              <p>
                <span class="fw-bold fs-5">이메일&nbsp; :</span>
                {{ user.email }}
              </p>
            </div>
          </div>
          <div class="row mb-5">
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <p class="fw-bold fs-5" style="text-align: center;">나를 팔로우 한 사람
                  <img style="width: 15px;" src="https://cdn-icons-png.flaticon.com/512/4344/4344892.png" alt=""></p>

                {% for myfollower in user.followers.all %}
                  <li class="list-group-item"><img class=" rounded-circle mx-2" src="{{ myfollower.user_img.url }}" style="width:50px;">{{ myfollower.username }}</li>
                {% endfor %}
              </ul>

              {% if not user.followers.all %}
                <p class="text-center">나를 팔로우 한 사람이 없습니다.</p>
              {% endif %}

            </div>
            <div class="col-md-6">
              <p class="fw-bold fs-5" style="text-align: center;">내가 팔로우 한 사람
                <img style="width: 15px;" src="https://cdn-icons-png.flaticon.com/512/4344/4344892.png" alt=""></p>
              <ul class="list-group list-group-flush">
                {% for myfollowing in user.followings.all %}
                  <li class="list-group-item"><img class=" rounded-circle mx-2" src="{{ myfollowing.user_img.url }}" style="width:50px;">{{ myfollowing.username }}</li>
                {% endfor %}
              </ul>

              {% if not user.followings.all %}
                <p class="text-center">내가 팔로우 한 사람이 없습니다.</p>
              {% endif %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/mypage_2.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <div class="">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h4 style="font-weight: bolder;" class="mt-4">회원 정보 보기</h4>
        </div>
      </div>
    </div>
  </div>
  <div class="mb-5 p-2">
    <div style="border-radius: 3%; border: 3px solid #FFED90;" class="container">
      <div class="row mt-4">
        <div class="col-md-12">
          <div class="row">
            <div class=" d-flex justify-content-center col-md-4">
              {% if user.user_img %}
                <img class="m-3 rounded-circle" src="{{ user.user_img.url }}" alt="{{ user.user_img }}" style="width:100px;">
              {% else %}
                <img class="m-3 rounded-circle" src="https://cdn-icons-png.flaticon.com/128/4484/4484346.png" alt="{{ user.user_img }}" style="width:100px;">
              {% endif %}
            </div>
            <div class="col-md-8">
              <div class="p-2 col-md-12">
                <div class="m-2">
                  <span class="fw-bold fs-4">{{ user.username }}</span>
                  <span class="m-3">팔로우
                    {{ user.followers.count }}
                    | 팔로잉
                    {{ user.followings.count }}
                  </span>
                  <span class="text-right">
                    {% if request.user != user %}
                      <a href="{% url 'accounts:follow' user.pk %}">
                        {% if request.user in user.followers.all %}
                          <button class="btn" style="background-color: #FFED90;" type="button">
                            팔로우 취소
                          </button>
                        {% else %}
                          <button class="btn" style="background-color: #FFED90;" type="button">
                            팔로우
                          </button>
                        {% endif %}
                      </a>
                    {% endif %}
                  </span>
                </div>
                <div class="m-2">
                  <p>{{ user.email }}</p>
                </div>
              </div>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-md-6">
              <div>
                <p class="fs-5" style="font-weight: bolder; text-align: center;">'{{ user.username }}' 님이 작성한 글
                  <img style="width: 15px;" src="https://cdn-icons-png.flaticon.com/512/4344/4344892.png" alt=""></p>
              </div>
              <ul class="list-group list-group-flush" style="list-style:none;">
                {% for review in user.review_set.all %}
                  <li class="mb-1" style="text-align: center;"><a href="{% url 'articles:r_detail' review.pk %}" class="text-text-decoration-none text-black">{{ review.title }}</a>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewbox="0 0 16 16">
                      <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                    </svg>
                  {% endfor %}
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <p class="fs-5" style="font-weight: bolder; text-align: center;">'{{ user.username }}' 님이 작성한 댓글
                <img style="width: 15px;" src="https://cdn-icons-png.flaticon.com/512/4344/4344892.png" alt=""></p>
              <ul class="list-group list-group-flush" style="list-style:none;">
                {% for comment in user.reviewcomment_set.all %}
                  <list style="text-align: center;">{{ comment.content }}</list>
                {% endfor %}
              </ul>
            </div>
          </div>
          <br>
          <hr class="m-2" style="background-color: #FFED90;">
          <div class="d-flex justify-content-between">
            <p class="m-4 fs-5" style="font-size: large; font-weight: bolder;">위시 리스트</p>
            <p class="m-4" href="#">더 보기 &nbsp<img style="width: 15px;" src="https://cdn-icons-png.flaticon.com/512/254/254434.png" alt=""></p>
          </div>


        
       
          <div class="d-flex justify-content-center flex-wrap">
            {% if user.product_wishlist.all %}
              {% for wish in user.product_wishlist.all %}
                <div class="card" style="width:18rem;">
                  <img class="card-img-top" src="{{ wish.image }}" alt="...">
                  <div class="card-body">
                    <p style="color: #B2B2B2;">카테고리</p>
                    <p style="color: #000; font-size: larger; font-weight: 400;" class="card-text">{{ wish.title }}</p>
                    <p>⭐⭐⭐⭐⭐</p>

                  </div>
                </div>
              {% endfor %}
            {% else %}
            </div>
            <p class="ms-4">상품이 없습니다.</p>
            <p class="ms-4 pb-3">
              <a href="{% url 'articles:product_main' %}">
                지금 떠날 여행 보러가기</a>
            </p>
          {% endif %}
          


        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %} 
<div class="py-5">
    <div class="container">
        <div style="border-radius: 3%; border: 3px solid #FFED90;" class="mx-auto col-md-6 col-10 bg-white p-5">
            <div class="text-center">
                <h1 style="color: #FFED90;" class="mb-3">누런 풍선</h1>
                <p>무거운 여행을 시작해 보세요 :) </p>
            </div>
            <div>
                <form action='' method='POST' enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="d-grid gap-2">
                    <button style="background-color: #FFED90;" type="submit" class="m-2 btn btn-lg">가입하기</button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
<div class="container py-5">
    <div style="border-radius: 3%; border: 3px solid #FFED90;" class="mx-auto col-md-6 col-10 bg-white p-5">
        <div class="text-center">
            <h1 style="color: #FFED90;" class="mb-3">누런 풍선</h1>
            <p>회원정보 수정페이지 :) </p>
        </div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-grid gap-2">
                <button style="background-color: #FFED90;" type="submit" class="m-3 btn btn-lg">회원정보 수정</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}