articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("c_create/<int:pk>", views.c_create, name="c_create"),
    path("c_delete/<int:a_pk>/<int:c_pk>", views.c_delete, name="c_delete"),
    path("like/<int:pk>", views.like, name="like"),
    path("notice/", views.notice, name="notice"),
    path("notice/n_create/", views.n_create, name="n_create"),
    path("notice/n_detail/<int:pk>", views.n_detail, name="n_detail"),
    path("notice/n_delete/<int:pk>", views.n_delete, name="n_delete"),
    path("notice/n_update/<int:pk>", views.n_update, name="n_update"),
    path("reviews/", views.reviews, name="reviews"),
    path("reviews/create", views.r_create, name="r_create"),
    path("reviews/<int:pk>", views.r_detail, name="r_detail"),
    path("reviews/delete/<int:pk>", views.r_delete, name="r_delete"),
    path("reviews/update/<int:pk>", views.r_update, name="r_update"),
    path("reviews/c_create/<int:pk>", views.r_c_create, name="r_c_create"),
    path("reviews/c_delete/<int:a_pk>/<int:c_pk>", views.r_c_delete, name="r_c_delete"),
    path("reviews/like/<int:pk>", views.r_like, name="r_like"),
    path("faq/", views.faq, name="faq"),
    path("faq/faq_create/", views.faq_create, name="faq_create"),
    path("faq/faq_detail/<int:pk>", views.faq_detail, name="faq_detail"),
    path("faq/faq_delete/<int:pk>", views.faq_delete, name="faq_delete"),
    path("faq/faq_update/<int:pk>", views.faq_update, name="faq_update"),
    path("search/", views.search, name="search"),
    path("searchfail/", views.searchfail, name="searchfail"),
    path("qna/", views.qna, name="qna"),
    path("qna/qna_create/", views.qna_create, name="qna_create"),
    path("qna/qna_detail/<int:pk>", views.qna_detail, name="qna_detail"),
    path("qna/qna_delete/<int:pk>", views.qna_delete, name="qna_delete"),
    path("qna/qna_update/<int:pk>", views.qna_update, name="qna_update"),
    path("qna_c_create/<int:pk>", views.qna_c_create, name="qna_c_create"),
    path("qna_c_delete/<int:a_pk>/<int:c_pk>", views.qna_c_delete, name="qna_c_delete"),
    path("product_main", views.product_main, name="product_main"),
    path("product_detail/<int:pk>", views.product_detail, name="product_detail"),
    path("wishlist/<int:pk>", views.wishlist, name="wishlist"),
    path("wishitem/<int:pk>", views.wishitem, name="wishitem"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, Thumbnail
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="articles/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )

    thumbnail = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[Thumbnail(200, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_articles"
    )


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Notice(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Review(models.Model):
    country = models.CharField(max_length=10)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    image_two = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    thumbnail = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[Thumbnail(400, 300)],
        format="JPEG",
        options={"quality": 80},
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_reviews"
    )
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_review"
    )


class ReviewComment(models.Model):
    content = models.TextField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Product(models.Model):
    title = models.CharField(max_length=100)
    image = ProcessedImageField(
        upload_to="reviews/",
        blank=True,
        processors=[Thumbnail(400, 300)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    wishlist = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="product_wishlist"
    )

    # def __str__(self):
    #     return self.title
    # def __str__(self):
    #     return self.wishlist

class WishItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Faq(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Qna(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(
        upload_to="images/%Y/%m/%d",
        blank=True,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 80},
        null=True,
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class QnaComment(models.Model):
    content = models.TextField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    qna = models.ForeignKey(Qna, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

articles/forms.py
from django import forms
from .models import Article, Comment, Notice, Review, ReviewComment, Faq, Qna, Product


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "image", "thumbnail"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "",
                    "style": "height: 40px; resize: none; width: 100%;",
                }
            ),
        }
        labels = {
            "content": "댓글",
        }


class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ["title", "content", "image"]


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["country", "title", "content", "grade", "image", "thumbnail"]
        labels = {
            "country": "다녀온 나라",
            "title": "후기 제목",
            "content": "후기 내용",
            "image": "사진 업로드",
            "grade": "이번 여행에 점수를 주자면? (1~5)",
            "thumbnail": "대표 사진",
        }


class ReviewCommentForm(forms.ModelForm):
    class Meta:
        model = ReviewComment
        fields = [
            "content",
        ]
        widgets = {
            "content": forms.Textarea(
                attrs={
                    "placeholder": "",
                    "style": "color: #c6c6c6; border: 1px solid #c6c6c6; height: 40px; resize: none; width: 45rem; padding: 0.4rem 0; display: inline-block;",
                }
            ),
        }
        labels = {
            "content": "댓글을 집력해주세요",
        }


class FaqForm(forms.ModelForm):
    class Meta:
        model = Faq
        fields = ["title", "content", "image"]


class QnaForm(forms.ModelForm):
    class Meta:
        model = Qna
        fields = ["title", "content", "image"]

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["title", "image"]

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %} 

<h1>3. 글 상세페이지</h1><hr>

<!-- 글 제목, 내용, 이미지-->
<p class='text-end'>{{ article.created_at }}</p>
<h1>{{ article.title }}</h1>
<p>{{ article.content }}</p>

{% if request.user == review.user %}
<a href="{% url 'articles:update' article.pk %}">수정</a>
<a href="{% url 'articles:delete' article.pk %}">삭제</a>
{% endif %}
<a href="{% url 'articles:index' %}">홈으로</a>
<div class='container text-center mt-5 mb-5'>
  {% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image }}" width="400" height="300"> {% endif %}
</div>
<hr>

<!-- 댓글 작성 -->
<form action="{% url 'articles:c_create' article.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form comment_form layout="inline" %}
  {% bootstrap_button button_type="submit" content="댓글작성" %}
</form>

<!-- 댓글 목록 -->
<h3 class='text-center'>댓글 목록</h3>
<hr>
{% for comment in comments %}
  <p>{{ comment.user }}  |  {{ comment.created_at }}  |  {{ comment.content }}  |  
    {% if request.user.is_authenticated %}
      {% if request.user == comment.user%}
        <a href="{% url 'articles:c_delete' article.pk comment.pk %}">삭제</a>
      {% endif %}
    {% endif %}
  </p>
{% empty %}
  <p>댓글이 없습니다 ㅠㅠ</p>
{% endfor %}

{% endblock %}

articles/templates/articles/n_detail.html
{% extends 'base2.html' %}
{% load django_bootstrap5 %}

{% block body %} 
    <!-- 공지 사항 -->
    <section style="padding: 60px 20px 20px 280px">
      <!-- 제목 -->
      <div>
        <h2 class="ms-3 fw-bold">공지사항</h2>
        <hr class="my-3" style="width: 9rem; color: black" />
        <p class="fw-semibold">홈페이지 공지사항입니다.</p>
      </div>
      <!-- 글 -->
      <section class="">
        <div class="p-3">
          <div
            class="rounded mt-3 p-5"
            style="width: 60rem; min-height: 30rem; border: 2.5px solid #ffed90"
          >
          {% if request.user.is_staff %}
            <!-- 수정, 삭제 -->
            <div class="fs-4 float-end">
              <a href="{% url 'articles:n_update' notice.pk %}"<i class="bi bi-pencil me-2" style="color: #2657ff"></i></a>
                <a href="{% url 'articles:n_delete' notice.pk %}"><i class="bi bi-trash" style="color: #e83c4b"></i></a>
            </div>
          {% endif %}

            <!-- 날짜와 제목 -->
            <p class="text-muted fw-semibold mb-0 ms-1">{{ notice.created_at }}</p>
            <p class="fw-bold fs-2">{{ notice.title }}</p>

            <!-- 후기 내용 -->
            <div class="mt-4 ms-1" style="min-height: 4rem">
              {{ notice.content }}
            </div>
            {% if notice.image %}
            <div class="my-4 mx-2 text-center">
              <img class="rounded me-3" style="width: 40rem; height: 40rem" src="{{ notice.image.url }}" alt="image">
            </div>
            {% endif %}
          </div>
        </div>
      </section>
      <!-- 글쓰기 버튼 -->
    </section>


{% endblock %}

articles/templates/articles/qna.html
{% extends 'base2.html' %}
{% load django_bootstrap5 %}

{% block body %}

  <!-- Q&A -->
  <section style="padding: 60px 20px 20px 280px">
    <!-- 제목 -->
    <div>
      <h2 class="ms-4 fw-bold">Q & A</h2>
      <hr class="my-3" style="width: 9rem; color: black"/>
      <p class="fw-semibold" style="white-space:nowrap;">홈페이지 운영에 관해 궁금하신 것 물어보세요.</p>
    </div>

    <!-- 글쓰기 버튼 -->
    <div class="mt-4" style="width: 93%; min-height:20rem;">
      <a href="{% url 'articles:qna_create' %}" class="btn fw-semibold float-end mb-3 px-3" style="background-color: #ffed90; text-color: black;">
        글쓰기
      </a>
      <!-- 테이블 -->
      <table class="table table-hover text-center" style="white-space:nowrap;">
        <thead class="table-group-divider">
          <tr style="font-size: 1.17rem">
            <th style="padding: 0.7rem 0.5rem 0.7rem 2rem; width: 6rem" scope="col">번호</th>
            <th style="padding: 0.7rem 2.8rem 0.7rem 4.5rem; width: 10rem" scope="col">작성자</th>
            <th style="padding: 0.7rem 0 0.7rem 8rem; width: 22rem" scope="col">제목</th>
            <th style="padding: 0.7rem 0 0.7rem 3.8rem " scope="col">답변여부</th>
            <th style="padding: 0.7rem 0 0.7rem 7.8rem" scope="col">작성시간</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          {% for qna in paginated_qnas %}
            <tr onclick="location.href=' {% url 'articles:qna_detail' qna.pk %} '" style='cursor: pointer;'>
              <td class="text-center" width:="width:" 6rem" scope=" row"=" row""="row""">{{ qna.pk }}</td>
              <td style=" padding: 0.7rem 2.5rem 0.7rem 1.5rem;">
                <p class="text-center" style="width: 9.5rem; white-space: nowrap; overflow: hidden;  margin-bottom:0;">{{ qna.user }}</p>
              </td>
              <td style="padding: 0.7rem 0 0.7rem 1rem;">
                <p style="width: 22rem; white-space: nowrap; overflow: hidden; text-overflow:ellipsis; margin-bottom:0;">{{ qna.title }}</p>
              </td>
              <td style="padding: 0.7rem 0 0.7rem 4rem">
                {% if qna.qnacomment_set.all %}
                  <span class="rounded fw-semibold" style="background-color: #FDC678; padding: 0.5rem 1rem">답변</span>
                {% else %}
                  <span class="rounded fw-semibold" style="background-color: #D9DFDF; padding: 0.5rem 1rem">답변</span>
                {% endif %}
              </td>
              <td style="padding: 0.7rem 0 0.7rem 4rem">{{ qna.created_at }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- 페이지네이션 -->
    <ul class="pagination justify-content-center">
      <!-- 첫 페이지 -->
      {% if paginated_qnas.has_previous %}
        <!-- 이전페이지가 있으면 연결(첫 페이지가 아니면) -->
        <li class="page-item">
          <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" tabindex="-1" href="?page=1">&#60;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" href="#">&#60;</a>
        </li>
      {% endif %}

      <!-- 페이지리스트 -->
      <!-- //페이지 범위를 하나씩 리턴 -->
      {% for page_number in paginated_qnas.paginator.page_range %}
        {% if page_number >= paginated_qnas.number|add:-2 and page_number <= paginated_qnas.number|add:2 %}
          <!-- // 현재 페이지일 때는 active -->
          {% if page_number == paginated_qnas.number %}
            <li class="page-item" aria-current="page">
              <a class="page-link mx-2 text-black rounded" style="border: none; background-color:#ffed90 !important;  padding: 0.5rem 1.05rem;" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
          {% else %}
            <li class="page-item text-color-warning">
              <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}

      <!-- 다음페이지 -->
      {% if paginated_notices.has_next %}
        <li class="page-item">
          <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" href="?page={{ max_index }}">&#62;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" tabindex="-1" href="#">&#62;</a>
        </li>
      {% endif %}
    </ul>

  </section>

{% endblock %}

articles/templates/articles/reviews.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <!-- 여행 카드 -->
  <div class="d-flex justify-content-center flex-wrap container pb-5 mt-5">
    {% if not paginated_reviews %}
    <div class="text-center" style="margin-top:10rem;">
    <h1>아직 리뷰가 없어요. </h1>
    <h1>리뷰를 남겨 여행의 즐거움을 나눠보세요 :)</h1>
  </div>
    {% endif %}
    {% for review in paginated_reviews %}
      <div class="card mx-4 my-3" style="width: 18rem; border:2px solid #FFED90">
        {% if request.user in review.like_users.all %}
          <a href="{% url 'articles:r_like' review.pk %}" class="position-absolute top-0 end-0" style="margin: 1rem 1rem 0rem 0; text-decoration: none">
            <i class="bi bi-heart-fill fs-4" style="color: #FF4040"></i>
          </a>
        {% else %}
          <a href="{% url 'articles:r_like' review.pk %}" class="position-absolute top-0 end-0" style="margin: 1rem 1rem 0rem 0; text-decoration: none">
            <i class="bi bi-heart fs-4" style="color: red;"></i>
          </a>
        {% endif %}
        {% if review.thumbnail %}
          <img src="{{ review.thumbnail.url }}" class="card-img-top" alt="{{ review.image }}" style='height: 10rem;'>
        {% else %}
          <img src="https://a.travel-assets.com/findyours-php/viewfinder/images/res70/84000/84621-Paris.jpg" class="card-img-top" alt="...">
        {% endif %}
        <div class="card-body" style="height: 15rem;">
          <p class="text-muted mb-0" style="font-size:0.8rem">'{{ review.country }}' 에 다녀와서...</p>
          <h4 class="card-title mt-0 mb-2">{{ review.title }}</h4>
          <h5 class="mb-3">
            {% if review.grade == 1 %}
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
            {% elif review.grade == 2 %}
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
            {% elif review.grade == 3 %}
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
            {% elif review.grade == 4 %}
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star" style="color: #ffed90"></i>
            {% elif review.grade == 5 %}
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
              <i class="bi bi-star-fill" style="color: #ffed90"></i>
            {% endif %}
          </h5>
          <p class="card-text fw-semibold" style="
      min-height: 3rem;
      text-overflow: ellipsis;
      overflow: hidden;
      word-break: break-word;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical">{{ review.content }}
          </p>
          <h1 class="float-end">
            <a href="{% url 'articles:r_detail' review.pk %}">
              <button class="btn p-0">
                <i class="bi bi-arrow-right-circle-fill fs-1" style="color:#FFED90;"></i>
              </button>
            </a>
          </h1>
        </div>
      </div>
    {% endfor %}
  </div>

  <!-- 페이지네이션 -->
  {% if paginated_reviews %}
  <ul class="pagination justify-content-center">
    <!-- 첫 페이지 -->
    {% if paginated_reviews.has_previous %}
      <!-- 이전페이지가 있으면 연결(첫 페이지가 아니면) -->
      <li class="page-item">
        <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" tabindex="-1" href="?page=1">&#60;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" href="#">&#60;</a>
      </li>
    {% endif %}

    <!-- 페이지리스트 -->
    <!-- //페이지 범위를 하나씩 리턴 -->
    {% for page_number in paginated_reviews.paginator.page_range %}
      {% if page_number >= paginated_reviews.number|add:-5 and page_number <= paginated_reviews.number|add:2 %}
          <!-- // 현재 페이지일 때는 active -->
          {% if page_number == paginated_reviews.number %}
            <li class="page-item" aria-current="page">
              <a class="page-link mx-2 text-black rounded" style="border: none; background-color:#ffed90 !important;  padding: 0.5rem 1.05rem;" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
          {% else %}
            <li class="page-item text-color-warning">
              <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
          {% endif %}
      {% endif %}
    {% endfor %}

    <!-- 다음페이지 -->
    {% if paginated_reviews.has_next %}
      <li class="page-item">
        <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" href="?page={{ max_index }}">&#62;</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link mx-2 text-black rounded" style="border: none; padding: 0.5rem 1.05rem;" tabindex="-1" href="#">&#62;</a>
      </li>
    {% endif %}
  </ul>
</div>
{% endif %}

<!-- 리뷰 작성 -->
<div class="sticky-bottom float-end me-4">
  <a class="btn fw-semibold px-3" style="font-size: 4rem" href="{% url 'articles:r_create' %}">
    <i class="bi bi-plus-circle-fill" style="color: #ffed90"></i>
  </a>
</div>

{{ country }}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

{% endblock %}

articles/templates/articles/searchfail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block body %}
  <div class="container d-flex justify-content-center mt-5">
    <div class="mt-5">
      <img style="width: 33rem; height:23rem; margin-left:-3rem;" src="{% static 'image/logo2.png' %}" alt="">
      <h1 class="mt-3" style="color:#636363">Oops! 검색 결과가 없어요 :(</h1>
    </div>
  </div>
{% endblock %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %} 

<h1>4. 글수정</h1><hr>

<form action='' method='POST' enctype="multipart/form-data>
  {% csrf_token %}
  {% bootstrap_form article_form %}
  {% bootstrap_button button_type='submit' content='수정하기' %}
</form>

{% endblock %}