accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mypage_1/<int:pk>/', views.mypage_1, name='mypage_1'),
    path('update/', views.update, name='update'),
    path('mypage_2/<int:pk>/', views.mypage_2, name='mypage_2'),
    path('<int:pk>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("detail/<int:pk>", views.detail, name="detail"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
    path("c_create/<int:pk>", views.c_create, name="c_create"),
    path("c_delete/<int:a_pk>/<int:c_pk>", views.c_delete, name="c_delete"),
    path("like/<int:pk>", views.like, name="like"),
    path("notice/", views.notice, name="notice"),
    path("notice/n_create/", views.n_create, name="n_create"),
    path("notice/n_detail/<int:pk>", views.n_detail, name="n_detail"),
    path("notice/n_delete/<int:pk>", views.n_delete, name="n_delete"),
    path("notice/n_update/<int:pk>", views.n_update, name="n_update"),
    path("reviews/", views.reviews, name="reviews"),
    path("reviews/create", views.r_create, name="r_create"),
    path("reviews/<int:pk>", views.r_detail, name="r_detail"),
    path("reviews/delete/<int:pk>", views.r_delete, name="r_delete"),
    path("reviews/update/<int:pk>", views.r_update, name="r_update"),
    path("reviews/c_create/<int:pk>", views.r_c_create, name="r_c_create"),
    path("reviews/c_delete/<int:a_pk>/<int:c_pk>", views.r_c_delete, name="r_c_delete"),
    path("reviews/like/<int:pk>", views.r_like, name="r_like"),
    path("faq/", views.faq, name="faq"),
    path("faq/faq_create/", views.faq_create, name="faq_create"),
    path("faq/faq_detail/<int:pk>", views.faq_detail, name="faq_detail"),
    path("faq/faq_delete/<int:pk>", views.faq_delete, name="faq_delete"),
    path("faq/faq_update/<int:pk>", views.faq_update, name="faq_update"),
    path("search/", views.search, name="search"),
    path("searchfail/", views.searchfail, name="searchfail"),
    path("qna/", views.qna, name="qna"),
    path("qna/qna_create/", views.qna_create, name="qna_create"),
    path("qna/qna_detail/<int:pk>", views.qna_detail, name="qna_detail"),
    path("qna/qna_delete/<int:pk>", views.qna_delete, name="qna_delete"),
    path("qna/qna_update/<int:pk>", views.qna_update, name="qna_update"),
    path("qna_c_create/<int:pk>", views.qna_c_create, name="qna_c_create"),
    path("qna_c_delete/<int:a_pk>/<int:c_pk>", views.qna_c_delete, name="qna_c_delete"),
    path("product_main", views.product_main, name="product_main"),
    path("product_detail/<int:pk>", views.product_detail, name="product_detail"),
    path("wishlist/<int:pk>", views.wishlist, name="wishlist"),
    path("wishitem/<int:pk>", views.wishitem, name="wishitem"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("articles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin">
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}">
    {% block css %}{% endblock css %}
    <link rel="stylesheet" type = "text/css" href="{% static '/css/style.css' %}">
    <title>Golden Balloon</title>
  </head>

  <body>
    <nav style="background-color: #FFED90; height:5.8rem" class="navbar navbar-expand-sm">
      <div class="container-fluid m-2 p-2">
        <div class="d-flex">
          <img style="width: 4rem; height:3rem;" src="{% static 'image/logo.png' %}" alt="">
          <a class="navbar-brand fw-bold fs-3" href="{% url 'articles:index' %}">누런 풍선</a>
        </div>
        <div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse m-2" id="navbarNavAltMarkup">
            <div class="navbar-nav" style="white-space:nowrap;">
              <a class="nav-link active text-black mx-2 fs-5 fw-semibold" aria-current="page" href="{% url 'articles:reviews' %}">리뷰목록</a>
              <a class="nav-link text-black mx-5 fs-5 fw-semibold" href="{% url 'articles:notice' %}">공지사항</a>

              <form action="{% url 'articles:search' %}">
                <div class="py-1 rounded me-4" style="background-color:#F7F3FA; display: inline-block;">
                  <i class="bi bi-search ms-3"></i>
                  <input class="pe-5 py-2 rounded" style="border:none; background-color:#F7F3FA;  outline: none; white-space:nowrap;" type="search" name="search" aria-label="Search" placeholder="검색해보세요">
                </div>
              </form>

              {% if request.user.is_authenticated %}
                <a class="nav-link fs-6 mt-1" href="{% url 'accounts:mypage_1' request.user.pk %}">{{ request.user }}</a>
                <a class="nav-link fs-6 mt-1" href="{% url 'accounts:logout' %}">로그아웃</a>
              {% else %}
                <a class="nav-link fs-6 mt-1" href="{% url 'accounts:login' %}">로그인</a>
                <a class="nav-link fs-6 mt-1 mx-2" href="{% url 'accounts:signup' %}">회원가입</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>

    {% block body %}{% endblock body %}

    <!-- footer -->
    <div class="py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <img style="width: 50px;" src="https://cdn-icons-png.flaticon.com/512/7682/7682764.png" alt="">
            <p style="font-size: 15px;">Golden Balloon</p>
            <p>
              <a style="text-decoration: none;" href="tel:+246 - 542 550 5462">10 TEAM</a>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 d-flex align-items-center justify-content-center my-3">
            <a style="text-decoration: none;" href="#">
              <span><img style="width: 25px;" src="https://cdn-icons-png.flaticon.com/512/220/220585.png" alt=""></span>
            </a>&nbsp&nbsp
            <a style="text-decoration: none;" href="#">
              <span><img style="width: 25px;" src="https://cdn-icons-png.flaticon.com/512/220/220607.png" alt=""></span>
            </a>&nbsp&nbsp
            <a style="text-decoration: none;" href="#">
              <span><img style="width: 25px;" src="https://cdn-icons-png.flaticon.com/512/220/220618.png" alt=""></span>
            </a>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">
            <p class="mb-0">© 2022</p>
          </div>
        </div>
      </div>
    </div>

  </body>

</html>

templates/base2.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin">
    <link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link href="{% static 'css/main10.css' %}" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css"/>

    <title>Golden Balloon</title>
  </head>

  <body>
    <nav style="background-color: #FFED90; height:5.8rem" class="navbar navbar-expand-sm">
      <div class="container-fluid m-2 p-2">
        <div class="d-flex">
          <img style="width: 4rem; height:3rem;" src="{% static 'image/logo.png' %}" alt="">
          <a class="navbar-brand fw-bold fs-3" href="{% url 'articles:index' %}">누런 풍선</a>
        </div>
        <div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse m-2" id="navbarNavAltMarkup">
            <div class="navbar-nav" style="white-space:nowrap;">
              <a class="nav-link active text-black mx-2 fs-5 fw-semibold" aria-current="page" href="{% url 'articles:reviews' %}">리뷰목록</a>
              <a class="nav-link text-black mx-5 fs-5 fw-semibold" href="{% url 'articles:notice' %}">공지사항</a>

              <div class="py-1 rounded me-4" style="background-color:#F7F3FA; display: inline-block;">
                <i class="bi bi-search ms-3"></i>
                <input class="pe-5 py-2 rounded" style="border:none; background-color:#F7F3FA;  outline: none; white-space:nowrap;" type="text" placeholder="검색해보세요">
              </div>

              {% if request.user.is_authenticated %}
                <a class="nav-link fs-6 mt-1" href="{% url 'accounts:mypage_1' request.user.pk %}">{{ request.user }}</a>
                <a class="nav-link fs-6 mt-1" href="{% url 'accounts:logout' %}">로그아웃</a>
              {% else %}
                <a class="nav-link fs-6 mt-1" href="{% url 'accounts:login' %}">로그인</a>
                <a class="nav-link fs-6 mt-1 mx-2" href="{% url 'accounts:signup' %}">회원가입</a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>

    <!-- 왼쪽 nav -->
    <div class="" style="
      width: 200px;
      border-right: 1px solid #8b8b8b;
      position: fixed;
      height: 100%;
    ">
      <ul style="
        list-style: none;
        padding-left: 0;
        margin-top: 5rem;
        color: #5f5e5e;
      " class="fw-bold fs-4 text-center">
        <li class="mb-5">
          <a href="{% url 'articles:notice' %}" style='text-decoration:none; color: #5f5e5e;'>공지사항</a>
        </li>
        <li class="mb-5">
          <a href="{% url 'articles:faq' %}" style='text-decoration:none; color: #5f5e5e;'>FAQ</a>
        </li>
        <li class="mb-5">
          <a href="{% url 'articles:qna' %}" style='text-decoration:none; color: #5f5e5e;'>Q & A</a>
        </li>
      </ul>
    </div>

    {% block body %}{% endblock body %}

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>

</html>

templates/nav.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NAV</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  </head>

  <body>
    <nav style="background-color: #FFED90;" class="navbar navbar-expand-lg">
      <div class="container-fluid m-2 p-2">
        <div style="float:left;">
          <img style="width: 50px;" src="{% static 'image/logo.png' %}" alt="">
          <a class="navbar-brand" href="#">누런 풍선</a>
          <input class="pe-5 " type="text" placeholder="검색해보세요.">
        </div>
        <div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse m-2" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="#">리뷰목록</a>
              <a class="nav-link" href="#">공지사항 / FQA</a>
              <a class="nav-link" href="#">로그인</a>
              <a class="nav-link disabled">회원가입/마이페이지</a>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

  </body>

</html>

templates/로그인.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">


</head>

<body>
   <!-- nav -->
   <nav style="background-color: #FFED90;" class="navbar navbar-expand-lg">
    <div class="container-fluid m-2 p-2">
        <div style="float:le;">
            <img style="width: 50px;" src="/image/로고고-removebg-preview.png" alt="">
            <a class="navbar-brand" href="#">누런 풍선</a>
            <input class="pe-5 " type="text" placeholder="검색해보세요.">
        </div>
        <div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse m-2" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  <a class="nav-link active" aria-current="page" href="#">리뷰목록</a>
                  <a class="nav-link" href="#">공지사항 / FQA</a>
                  <a class="nav-link" href="#">로그인</a>
                  <a class="nav-link disabled">회원가입/마이페이지</a>
                </div>
              </div>
        </div>
    </div>
  </nav>

  <div class="py-5 text-center">
    <div class="py-5 container">
      <div class="row">
        <div style="border-radius: 3%; border: 3px solid #FFED90;" class="mx-auto col-md-6 col-10 bg-white p-5">
          <h2 style="color: #FFED90;" class="mb-3">누런 풍선</h2>
          <p>무거운 여행을 시작해 보세요 :) </p>
          <form>
            <div class="form-group mb-3"> <input style="border-radius: 3%; border: 3px solid #FFED90;" type="email" class="form-control" placeholder="아이디를 입력해주세요." id="form9"> </div>
            <div class="form-group mb-3"> <input style="border-radius: 3%; border: 3px solid #FFED90;" type="password" class="form-control" placeholder="비밀번호를 입력해주세요." id="form10">
              <br>
              <small>
                <span>혹시 회원이 아니신가요? <a style="text-decoration: none;" href="#">회원 가입</a>하기</span>
              </small>
            </div> 
            <button style="background-color: #FFED90;" type="button" class="m-2 btn btn-lg">✈ 바로 시작 ✈</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>


</body>

</html>

templates/마이페이지1.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>

<body>
   <!-- nav -->
   <nav style="background-color: #FFED90;" class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <div style="float:le;">
            <img style="width: 50px;" src="/image/로고고-removebg-preview.png" alt="">
            <a class="navbar-brand" href="#">누런 풍선</a>
            <input class="pe-5 " type="text" placeholder="검색해보세요.">
        </div>
        <div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse m-2" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                  <a class="nav-link active" aria-current="page" href="#">리뷰목록</a>
                  <a class="nav-link" href="#">공지사항 / FQA</a>
                  <a class="nav-link" href="#">로그인</a>
                  <a class="nav-link disabled">회원가입/마이페이지</a>
                </div>
              </div>
        </div>
    </div>
  </nav>

  <!-- <div class="p-md-0">
    <div class="container">
        <div class="m-3">
            <h4> 프로필 관리</h4>
        </div>
    </div>
  </div>
   -->

  <!-- <div class="container bg-black"> -->
    <div class="py-5">
    <div style="border-radius: 3%; border: 3px solid #FFED90;" class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-4"></div>
            <div class="d-flex justify-content-center col-md-4">
              <img class="m-3 rounded-circle" src="https://cdn-icons-png.flaticon.com/128/4140/4140065.png" style="width:100px;">
            </div>
            <div class="col-md-4 text-right p-3">
              <a style="border: 3px solid #FFED90;" class="btn" href="#">편집하기</a>
            </div>
          </div>
          <div class="row">
            <div class="m-2 col-md-12">
              <p>닉네임&nbsp; : 안녕
                <br><br>
                이메일&nbsp; : hi@gamil.com
                <br><br> 
                비밀번호&nbsp; : ************** </p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <p style="text-align: center;">나를 팔로우 한 사람 <img style="width: 15px;" src="https://cdn-icons-png.flaticon.com/512/4344/4344892.png" alt=""></p>
                <li class="list-group-item"><img class=" rounded-circle" src="https://cdn-icons-png.flaticon.com/512/4140/4140048.png" style="width:50px;">&nbsp&nbsp김00&nbsp;</li>
                <li class="list-group-item"><img class=" rounded-circle" src="https://cdn-icons-png.flaticon.com/128/4140/4140051.png" style="width:50px;">&nbsp&nbsp김00&nbsp;</li>
                <li class="list-group-item"><img class=" rounded-circle" src="https://cdn-icons-png.flaticon.com/128/4140/4140077.png" style="width:50px;">&nbsp&nbsp김00&nbsp;</li>
              </ul>
            </div>
            <div class="col-md-6">
              <p style="text-align: center;">내가 팔로우 한 사람 <img style="width: 15px;" src="https://cdn-icons-png.flaticon.com/512/4344/4344892.png" alt=""></p>
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><img class=" rounded-circle" src="https://cdn-icons-png.flaticon.com/128/4140/4140061.png" style="width:50px;">&nbsp&nbsp김00&nbsp;</li>
                <li class="list-group-item"><img class=" rounded-circle" src="https://cdn-icons-png.flaticon.com/128/4139/4139981.png" style="width:50px;">&nbsp&nbsp김00&nbsp;</li>
                <li class="list-group-item"><img class=" rounded-circle" src="https://cdn-icons-png.flaticon.com/128/4139/4139951.png" style="width:50px;">&nbsp&nbsp김00&nbsp;</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- </div> -->
  
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</body>

</html>

templates/메인.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAIN</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <!-- nav -->
    <nav style="background-color: #FFED90;" class="navbar navbar-expand-lg">
        <div class="container-fluid m-2 p-2">
            <div style="float:left;">
                <img style="width: 50px;" src="/STATIC/imege/로고고-removebg-preview.png" alt="">
                <a class="navbar-brand" href="#">누런 풍선</a>
                <input class="pe-5 " type="text" placeholder="검색해보세요.">
            </div>
            <div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse m-2" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                      <a class="nav-link active" aria-current="page" href="#">리뷰목록</a>
                      <a class="nav-link" href="#">공지사항 / FQA</a>
                      <a class="nav-link" href="#">로그인</a>
                      <a class="nav-link disabled">회원가입/마이페이지</a>
                    </div>
                  </div>
            </div>
        </div>
      </nav>

     <!-- JavaScript Bundle with Popper -->
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>